project:
  type: website

website:
  title: "Sound-Net"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: documentation/index.qmd
        text: Documentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
